### ISSUE TITLE
code review  

### ISSUE THREAD

**Issue by Amalcxc** [kensayo/to-do-list#3]
- finish the project

**Comment by lfmnovaes** [comment]
## Great work on your project Kenny 🙌 

It's really cool that you are using JQuery and Bootstrap as a module of webpack 😃

I have a few suggestions to improve the README.md of your project because I couldn't find any issue with your code.
- It would look better `git clone https://github.com/kensayo/to-do-list.git` inside code mark
- Other steps could be `npm install` and `npm start`
- You can create a subtopic Usage to describe that anyone can just open the `index.html` inside the dist folder

One more thing that I noticed, but now it's from your `package.json` file:
- If you are not using lodash on your project, you can remove it by `npm uninstall --save-dev lodash`

### Keep the good work 👍

**Comment by kensayo** [comment]
Thank for suggestions, fixed.
